---
title: "Lab 1"
author: "Elean Rivas, Javier Alvarez"
date: "2023-07-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(ggplot2)
library(dplyr)
library(corrplot)
```
1. Analisis exploratorio rapido

```{r}
library(readr)
library(ggplot2)
library(dplyr)


dataset <- read.csv("risk_factors_cervical_cancer.csv", na.strings = c("", "NA"))

str(dataset)

summary(dataset)

head(dataset)


tail(dataset)

colSums(is.na(dataset))

table(dataset$Smokes)

table(dataset$Dx.Cancer, dataset$Smokes)

hist(dataset$Age)


ggplot(dataset, aes(x = Age)) + geom_histogram(binwidth = 5, fill = "blue", color = "black") + labs(title = "Age Distribution", x = "Age")

ggplot(dataset, aes(x = Number.of.sexual.partners, fill = Smokes)) + geom_bar() + labs(title = "Number of Sexual Partners by Smoking Status", x = "Number of Sexual Partners", y = "Count")
```
2. Clasificación de los tipos de variables

```{r}
get_variable_types <- function(data) {
  sapply(data, class)
}

variable_types <- get_variable_types(dataset)

numerical_vars <- names(dataset)[sapply(dataset, is.numeric)]
categorical_vars <- names(dataset)[sapply(dataset, is.factor) | sapply(dataset, is.character)]

print("Variable Types:")
print(variable_types)

print("Numerical Variables:")
print(numerical_vars)

print("Categorical Variables:")
print(categorical_vars)
```

3. Incluya gráficos de exploración de las variables numericas
```{r}
for (var in numerical_vars) {
  p <- ggplot(dataset, aes(x = !!as.name(var))) +
    geom_histogram(binwidth = 5, fill = "blue", color = "black") +
    labs(title = paste("Histogram of", var), x = var, y = "Count")
  print(p)
}
```
4.Haga una correlación de las varaibles númericas

```{r}
numerical_vars <- names(dataset)[sapply(dataset, is.numeric)]

numerical_data <- dataset[, numerical_vars]

correlation_matrix <- cor(numerical_data, use = "pairwise.complete.obs")

print("Correlation Matrix:")
print(correlation_matrix)
corrplot(correlation_matrix, method = "color", type = "upper", tl.cex = 0.7)

```
